-- support_faq refresh dev / phpMyAdmin import
SET NAMES utf8mb4;
START TRANSACTION;

UPDATE `support_faq` SET `position` = 1, `nom` = 'Pourquoi utiliser Cotton ?', `descriptif_long` = '<p><b>Cotton permet de programmer facilement des animations conviviales et interactives</b> pour des établissements, des entreprises, des organisateurs d\'événements ou des particuliers.</p><p>Tu choisis un jeu, tu sélectionnes un contenu adapté à ton public, puis tu lances une session simple à prendre en main, agréable à partager et rapide à préparer.</p><p>La plateforme est pensée pour faire gagner du temps tout en proposant des expériences ludiques et variées.</p>', `date_maj` = NOW() WHERE `id` = 3;
UPDATE `support_faq` SET `position` = 2, `nom` = 'À qui s’adresse Cotton ?', `descriptif_long` = '<p>Cotton s\'adresse à toutes les personnes qui veulent organiser une animation autour du jeu : <b>établissements</b>, <b>entreprises</b>, <b>organisateurs d\'événements</b> et <b>particuliers</b>.</p><p>La solution convient aussi bien à un rendez-vous régulier, à un événement ponctuel, à une soirée privée ou à une animation professionnelle.</p>', `date_maj` = NOW() WHERE `id` = 26;
UPDATE `support_faq` SET `position` = 4, `nom` = 'Quels jeux puis-je proposer ?', `descriptif_long` = '<p>Avec Cotton, tu peux programmer trois jeux : <b>Blind Test</b>, <b>Bingo Musical</b> et <b>Cotton Quiz</b>.</p><p>Selon le jeu choisi, tu peux retrouver des formats <b>numériques</b> ou <b>classiques</b> afin d\'adapter l\'animation à ton public et à ton contexte.</p>', `date_maj` = NOW() WHERE `id` = 4;
UPDATE `support_faq` SET `position` = 5, `nom` = 'Quelle est la durée d’une animation Cotton ?', `descriptif_long` = '<p>Dans leur configuration standard, les jeux Cotton durent <b>environ 30 minutes</b>.</p><ul><li><b>Blind Test</b> : playlist de <b>40 extraits de 30 secondes</b> par défaut.</li><li><b>Bingo Musical</b> : playlist de <b>40 extraits de 30 secondes</b> par défaut.</li><li><b>Cotton Quiz</b> : jusqu\'à <b>4 séries</b>, soit <b>24 questions d\'environ 1 minute</b> dans le format complet par défaut.</li></ul><p>Ces durées peuvent ensuite être adaptées selon les réglages choisis.</p>', `date_maj` = NOW() WHERE `id` = 5;
UPDATE `support_faq` SET `position` = 6, `nom` = 'Comment choisir les contenus de mes animations ?', `descriptif_long` = '<p>Depuis les catalogues de jeux, tu peux parcourir toutes les thématiques disponibles et explorer les sélections <b>À la une</b>, <b>Nouveautés</b> ou choisir par <b>Thèmes</b>.</p><p>Tu peux partir d\'un contenu prêt à jouer ou sélectionner une thématique précise selon ton public, ton ambiance ou ton événement.</p>', `date_maj` = NOW() WHERE `id` = 6;
UPDATE `support_faq` SET `position` = 8, `nom` = 'Comment communiquer sur mes animations et attirer des joueurs ?', `descriptif_long` = '<p><b>Partage les liens de tes sessions</b> en amont sur tes réseaux, dans tes invitations ou auprès de tes participants pour leur permettre de découvrir et de rejoindre facilement tes animations.</p><p><b>Utilise les supports visuels</b> mis à disposition dans ton espace pour annoncer tes rendez-vous, et <b>diffuse les écrans de jeu</b> le jour J pour rendre l\'animation visible sur place.</p><p>Selon le contexte, certaines sessions peuvent aussi être visibles dans l\'agenda Cotton.</p>', `date_maj` = NOW() WHERE `id` = 27;
UPDATE `support_faq` SET `position` = 9, `nom` = 'Comment mettre à jour les informations publiées sur le site ?', `descriptif_long` = '<p>Depuis ton espace Cotton, tu peux mettre à jour les informations liées à ton <b>lieu</b>, à ton <b>événement</b> et aux éléments visibles sur les supports associés à tes animations.</p><p>Pense à vérifier régulièrement tes informations pratiques et tes visuels pour garder une présentation cohérente et à jour.</p>', `date_maj` = NOW() WHERE `id` = 7;
UPDATE `support_faq` SET `position` = 10, `nom` = 'Je souhaite organiser des jeux dans plusieurs lieux, est-ce possible ?', `descriptif_long` = '<p><b>Oui, c\'est possible.</b></p><p>Si tu organises des animations dans plusieurs lieux, sur plusieurs dates ou pour plusieurs structures, Cotton peut s\'adapter à ton organisation. <b>Contacte-nous</b> pour définir la formule la plus adaptée à ton réseau, à ton événement ou à ton usage multi-sites.</p>', `date_maj` = NOW() WHERE `id` = 8;
UPDATE `support_faq` SET `nom` = 'Comment animer les jeux Cotton ?', `descriptif_long` = '<p>Les jeux Cotton sont conçus pour être <b>simples à lancer et faciles à animer</b>.</p><p>Présente rapidement le principe du jeu, rappelle les règles essentielles, annonce les éventuels lots puis lance la session. Ensuite, tu peux choisir un rythme d\'animation très léger ou intervenir davantage pour faire vivre la partie selon ton style et ton public.</p>', `date_maj` = NOW() WHERE `id` = 21;
UPDATE `support_faq` SET `nom` = 'Faut-il un équipement spécifique pour organiser les animations Cotton ?', `descriptif_long` = '<p>Un <b>ordinateur</b> ou un <b>smartphone connecté</b> suffit pour lancer une session.</p><p>Pour une meilleure expérience, il est conseillé d\'utiliser un <b>écran visible par tous</b>. Selon le format choisi, les participants jouent ensuite sur <b>smartphone</b> ou avec des <b>supports papier</b>.</p>', `date_maj` = NOW() WHERE `id` = 22;
UPDATE `support_faq` SET `nom` = 'Quels sont les lots à gagner ?', `descriptif_long` = '<p><b>Il n\'y a pas de règle imposée.</b> C\'est toi qui choisis les lots adaptés à ton animation et à ton public.</p><p>Tu peux prévoir un lot unique, plusieurs gains selon les phases du jeu, ou simplement miser sur l\'aspect convivial de l\'animation. L\'important est d\'annoncer clairement ce qui est en jeu avant le début de la partie.</p>', `date_maj` = NOW() WHERE `id` = 23;
UPDATE `support_faq` SET `nom` = 'Quels conseils pouvez-vous me donner pour bien animer mon Cotton Quiz ?', `descriptif_long` = '<p><b>Présente le format et le nombre de séries avant de commencer</b>, puis donne un rythme clair à la session.</p><p>Prends le temps de lire les questions, annonce les pauses prévues entre les séries si tu en utilises, et garde une animation fluide pour maintenir l\'attention des joueurs tout au long du quiz.</p>', `date_maj` = NOW() WHERE `id` = 24;
UPDATE `support_faq` SET `nom` = 'Quels conseils pouvez-vous me donner pour bien animer mon Bingo Musical ?', `descriptif_long` = '<p><b>Annonce les phases à gagner</b> avant de commencer : <b>Ligne</b>, <b>Double ligne</b> puis <b>Bingo</b>.</p><p>Tu peux faire varier la durée des extraits pour pimenter la partie et prévoir de petites pauses après une phase gagnée. N\'hésite pas à interagir avec les joueurs pour garder une ambiance festive et dynamique.</p>', `date_maj` = NOW() WHERE `id` = 25;
UPDATE `support_faq` SET `nom` = 'Qu’est-ce que le championnat Inter-bars de Cotton Quiz ?', `descriptif_long` = '<p>Le <b>Championnat Inter-bars</b> correspond à un format d\'animation permettant d\'inscrire des sessions de Cotton Quiz dans une dynamique plus large entre plusieurs établissements participants.</p><p>Selon les opérations en cours, il peut valoriser les résultats obtenus pendant les animations organisées dans les établissements concernés.</p>', `date_maj` = NOW() WHERE `id` = 13;
UPDATE `support_faq` SET `nom` = 'Comment sont sélectionnées les équipes ?', `descriptif_long` = '<p>Lorsque le Championnat Inter-bars est actif, la sélection des équipes repose sur les résultats obtenus lors des sessions concernées.</p><p>Les modalités exactes peuvent varier selon l\'opération en cours. Elles sont précisées dans les supports et espaces dédiés lorsque ce format est proposé.</p>', `date_maj` = NOW() WHERE `id` = 14;
UPDATE `support_faq` SET `nom` = 'À quel moment se déroulent les finales ?', `descriptif_long` = '<p>Le calendrier des finales dépend des opérations de Championnat Inter-bars en cours.</p><p>Lorsque ton établissement ou ton événement participe à ce format, les dates utiles et les modalités d\'organisation sont précisées dans les espaces et supports dédiés.</p>', `date_maj` = NOW() WHERE `id` = 15;
UPDATE `support_faq` SET `nom` = 'Quelle est la durée d’un Cotton Quiz ?', `descriptif_long` = '<p>Un Cotton Quiz dure en général <b>environ 30 minutes</b> dans son format standard.</p><p>Tu peux composer ton quiz avec <b>jusqu\'à 4 séries</b>. Dans le format complet par défaut, cela correspond à <b>24 questions</b>, soit <b>4 séries de 6 questions</b> d\'environ <b>1 minute</b> chacune.</p>', `date_maj` = NOW() WHERE `id` = 9;
UPDATE `support_faq` SET `nom` = 'Comment choisir le contenu de mon Cotton Quiz ?', `descriptif_long` = '<p>Tu peux choisir une thématique depuis les catalogues de jeux, explorer les sélections <b>À la une</b>, <b>Nouveautés</b> et <b>Thèmes</b>, ou créer ton propre contenu.</p><p>Il est aussi possible de créer une <b>série de quiz personnalisée</b> avec tes propres questions, réponses, fausses propositions et supports média.</p>', `date_maj` = NOW() WHERE `id` = 10;
UPDATE `support_faq` SET `nom` = 'Comment fonctionne le système de points ?', `descriptif_long` = '<p>Dans un Cotton Quiz, <b>chaque bonne réponse rapporte 10 points</b>.</p><p>L\'objectif est de cumuler le plus de points possible au fil des séries pour terminer en tête du classement final.</p>', `date_maj` = NOW() WHERE `id` = 11;
UPDATE `support_faq` SET `nom` = 'Quelles sont les règles du jeu ?', `descriptif_long` = '<p>Le Cotton Quiz est disponible en version <b>numérique</b> et en version <b>classique</b>.</p><p>Tu peux régler la durée des questions entre <b>30 secondes</b> et <b>1 minute</b>. En version numérique, tu peux afficher de <b>2 à 4 propositions de réponse</b> aux joueurs. Tu peux aussi définir un temps de pause entre les séries, de <b>0 à 15 minutes</b>.</p><p>Le quiz peut être composé de plusieurs séries, dans la limite de <b>4 séries</b>.</p>', `date_maj` = NOW() WHERE `id` = 12;
UPDATE `support_faq` SET `nom` = 'Quelle est la durée d’un Bingo Musical ?', `descriptif_long` = '<p>Un Bingo Musical dure en général <b>environ 30 minutes</b> dans son format standard.</p><p>Par défaut, il repose sur une playlist de <b>40 extraits de 30 secondes</b>. Tu peux ensuite régler la durée des extraits entre <b>10 et 30 secondes</b>, et choisir au cas par cas de laisser jouer <b>un morceau en entier</b> si tu le souhaites.</p>', `date_maj` = NOW() WHERE `id` = 16;
UPDATE `support_faq` SET `nom` = 'Comment choisir le contenu de mon Bingo Musical ?', `descriptif_long` = '<p>Depuis les catalogues de jeux, tu peux sélectionner une thématique adaptée à ton public parmi les playlists disponibles.</p><p>Tu peux aussi créer une <b>playlist personnalisée</b> à partir d\'une <b>URL de playlist YouTube Music</b> pour construire une animation plus sur mesure.</p>', `date_maj` = NOW() WHERE `id` = 17;
UPDATE `support_faq` SET `nom` = 'Comment se déroule un Bingo Musical ?', `descriptif_long` = '<p>Le Bingo Musical se joue par phases : <b>Ligne</b>, <b>Double ligne</b> puis <b>Bingo</b>.</p><p>Les joueurs doivent reconnaître les morceaux diffusés et compléter correctement leur grille au fil de la partie. <b>Le ou la premier·e qui complète correctement une phase remporte cette phase.</b></p>', `date_maj` = NOW() WHERE `id` = 18;
UPDATE `support_faq` SET `nom` = 'Comment fonctionnent les grilles de jeu ?', `descriptif_long` = '<p>En version <b>numérique</b>, les joueurs utilisent des <b>grilles sur smartphone</b>. En version <b>classique</b>, ils jouent avec des <b>grilles sur papier</b>.</p><p>Le nombre de grilles disponibles dépend du nombre de joueurs prévu pour ta session.</p>', `date_maj` = NOW() WHERE `id` = 19;
UPDATE `support_faq` SET `nom` = 'Comment se passe la validation des grilles de jeu ?', `descriptif_long` = '<p>En version <b>numérique</b>, la validation des phases est <b>gérée automatiquement</b> par l\'application.</p><p>En version <b>classique</b>, la validation se fait par l\'animateur, à partir du tableau de contrôle. Dans tous les cas, <b>la première personne à compléter correctement une phase gagne la phase correspondante</b>.</p>', `date_maj` = NOW() WHERE `id` = 20;
UPDATE `support_faq` SET `nom` = 'Principe du Bingo Musical', `descriptif_long` = '<p><b>Chaque grille de jeu est unique</b> et se compose de morceaux choisis dans la playlist de la session.</p><p>Les joueurs doivent reconnaître les morceaux diffusés puis repérer ceux qui sont présents sur leur grille.</p><p>L\'objectif est d\'être le ou la premier·e à compléter correctement une <b>Ligne</b>, puis une <b>Double ligne</b>, puis un <b>Bingo</b>.</p>', `date_maj` = NOW() WHERE `id` = 28;
UPDATE `support_faq` SET `nom` = 'Règles du jeu', `descriptif_long` = '<p>Les joueurs utilisent des <b>grilles papier</b>. La partie se déroule en trois phases : <b>Ligne</b>, <b>Double ligne</b> puis <b>Bingo</b>.</p><p><b>Le ou la premier·e qui complète correctement une phase remporte cette phase.</b> En version classique, la validation est faite par l\'animateur à partir du tableau de contrôle.</p><p>Tu peux régler la durée des extraits entre <b>10 et 30 secondes</b> et laisser jouer un morceau en entier lorsque tu le souhaites.</p>', `date_maj` = NOW() WHERE `id` = 29;
UPDATE `support_faq` SET `nom` = 'Conseils d\'animation', `descriptif_long` = '<p><b>Annonce les phases à gagner et les lots avant le début de la partie.</b></p><p>Prévois une consigne simple pour départager deux gagnants simultanés si nécessaire. Tu peux aussi marquer de petites pauses après une phase gagnée et faire varier la durée des extraits pour dynamiser l\'animation.</p>', `date_maj` = NOW() WHERE `id` = 30;
UPDATE `support_faq` SET `nom` = 'Principe du Bingo Musical', `descriptif_long` = '<p><b>Chaque grille de jeu est unique</b> et se compose de morceaux choisis dans la playlist de la session.</p><p>Les joueurs doivent reconnaître les morceaux diffusés puis repérer ceux qui sont présents sur leur grille.</p><p>L\'objectif est d\'être le ou la premier·e à compléter correctement une <b>Ligne</b>, puis une <b>Double ligne</b>, puis un <b>Bingo</b>.</p>', `date_maj` = NOW() WHERE `id` = 31;
UPDATE `support_faq` SET `nom` = 'Règles du jeu', `descriptif_long` = '<p>Les joueurs utilisent des <b>grilles sur smartphone</b>. La partie se déroule en trois phases : <b>Ligne</b>, <b>Double ligne</b> puis <b>Bingo</b>.</p><p><b>Le ou la premier·e qui complète correctement une phase remporte cette phase.</b> En version numérique, la validation est gérée automatiquement par l\'application.</p><p>Tu peux régler la durée des extraits entre <b>10 et 30 secondes</b> et laisser jouer un morceau en entier lorsque tu le souhaites.</p>', `date_maj` = NOW() WHERE `id` = 32;
UPDATE `support_faq` SET `nom` = 'Conseils d\'animation', `descriptif_long` = '<p><b>Le principe du jeu est visible sur les grilles, mais une annonce orale reste toujours utile.</b></p><p>Annonce les lots, rappelle les phases à gagner et n\'hésite pas à faire varier la durée des extraits ou à marquer une pause après une phase gagnée pour rythmer la partie.</p>', `date_maj` = NOW() WHERE `id` = 33;
UPDATE `support_faq` SET `nom` = 'Principe du jeu', `descriptif_long` = '<p>Le Blind Test est un jeu musical basé sur la rapidité. Les joueurs doivent reconnaître le bon morceau, le bon titre ou le bon artiste au fil des extraits proposés.</p><p>Dans sa configuration standard, une session dure <b>environ 30 minutes</b>, sur la base de <b>40 extraits de 30 secondes</b> par défaut.</p>', `date_maj` = NOW() WHERE `id` = 40;
UPDATE `support_faq` SET `nom` = 'Règles du jeu', `descriptif_long` = '<p>Le Blind Test existe en version <b>numérique</b> et en version <b>classique</b>. En version numérique, les joueurs répondent sur smartphone. En version classique, les réponses se font sur papier.</p><p>Chaque bonne réponse rapporte <b>entre 1 et 10 points</b> selon le temps de réponse. Tu peux régler la durée des extraits entre <b>10 et 30 secondes</b>. En version numérique, tu peux afficher de <b>3 à 5 propositions</b> et choisir un affichage <b>titre + artiste</b> ou <b>titres uniquement</b>. Tu peux aussi laisser jouer un morceau en entier lorsque tu le souhaites.</p>', `date_maj` = NOW() WHERE `id` = 41;
UPDATE `support_faq` SET `nom` = 'Conseils', `descriptif_long` = '<p><b>Présente rapidement le fonctionnement avant le départ</b> et annonce les lots si tu en prévois.</p><p>Pour une animation plus fluide et interactive, privilégie le format numérique. Pour un fonctionnement plus libre ou plus traditionnel, le format classique convient très bien.</p>', `date_maj` = NOW() WHERE `id` = 42;
UPDATE `support_faq` SET `nom` = 'Principe du Cotton Quiz', `descriptif_long` = '<p>Le Cotton Quiz est un jeu de questions-réponses organisé en séries, sur des thématiques variées.</p><p>Dans son format standard complet, une session dure <b>environ 30 minutes</b>. Chaque bonne réponse rapporte <b>10 points</b>.</p>', `date_maj` = NOW() WHERE `id` = 34;
UPDATE `support_faq` SET `nom` = 'Règles du jeu', `descriptif_long` = '<p>Le Cotton Quiz est disponible en version <b>numérique</b> et en version <b>classique</b>.</p><p>Tu peux composer ton quiz avec plusieurs séries, dans la limite de <b>4 séries</b>. Tu peux régler la durée des questions entre <b>30 secondes</b> et <b>1 minute</b>. En version numérique, tu peux afficher de <b>2 à 4 propositions de réponse</b> aux joueurs. Tu peux aussi définir un temps de pause entre les séries, de <b>0 à 15 minutes</b>.</p>', `date_maj` = NOW() WHERE `id` = 35;
UPDATE `support_faq` SET `nom` = 'Conseils d\'animation', `descriptif_long` = '<p><b>Présente le nombre de séries et le rythme de la partie avant de commencer.</b></p><p>Pour un format plus court, réduis le nombre de séries. Pour une animation plus complète, conserve plusieurs séries et annonce les pauses à l\'avance si tu en utilises.</p>', `date_maj` = NOW() WHERE `id` = 36;
UPDATE `support_faq` SET `nom` = 'Principe du Cotton Quiz', `descriptif_long` = '<p>Le Cotton Quiz est un jeu de questions-réponses organisé en séries, sur des thématiques variées.</p><p>Dans son format standard complet, une session dure <b>environ 30 minutes</b>. Chaque bonne réponse rapporte <b>10 points</b>.</p>', `date_maj` = NOW() WHERE `id` = 37;
UPDATE `support_faq` SET `nom` = 'Règles du jeu', `descriptif_long` = '<p>Le Cotton Quiz est disponible en version <b>numérique</b> et en version <b>classique</b>.</p><p>Tu peux composer ton quiz avec plusieurs séries, dans la limite de <b>4 séries</b>. Tu peux régler la durée des questions entre <b>30 secondes</b> et <b>1 minute</b>. En version numérique, tu peux afficher de <b>2 à 4 propositions de réponse</b> aux joueurs. Tu peux aussi définir un temps de pause entre les séries, de <b>0 à 15 minutes</b>.</p>', `date_maj` = NOW() WHERE `id` = 38;
UPDATE `support_faq` SET `nom` = 'Conseils d\'animation', `descriptif_long` = '<p><b>Présente le nombre de séries et le rythme de la partie avant de commencer.</b></p><p>Pour un format plus court, réduis le nombre de séries. Pour une animation plus complète, conserve plusieurs séries et annonce les pauses à l\'avance si tu en utilises.</p>', `date_maj` = NOW() WHERE `id` = 39;

INSERT INTO `support_faq` (`id`, `id_sous_domaine`, `id_type_produit`, `zoning_code`, `position`, `online`, `nom`, `descriptif_long`, `date_ajout`, `date_maj`, `id_user_ajout`, `id_user_maj`) VALUES (43, 4, 0, 'account', 10, 0, 'Que puis-je gérer depuis mon compte Cotton ?', '<p>Depuis ton compte Cotton, tu peux gérer les informations de ton espace, programmer tes sessions, choisir tes jeux et contenus, et personnaliser les visuels associés à tes animations.</p><p>Tu retrouves aussi les sessions déjà programmées et les contenus que tu utilises régulièrement.</p>', NOW(), NOW(), 0, 0) ON DUPLICATE KEY UPDATE `id_sous_domaine` = VALUES(`id_sous_domaine`), `id_type_produit` = VALUES(`id_type_produit`), `zoning_code` = VALUES(`zoning_code`), `position` = VALUES(`position`), `online` = VALUES(`online`), `nom` = VALUES(`nom`), `descriptif_long` = VALUES(`descriptif_long`), `date_maj` = NOW(), `id_user_maj` = VALUES(`id_user_maj`);
INSERT INTO `support_faq` (`id`, `id_sous_domaine`, `id_type_produit`, `zoning_code`, `position`, `online`, `nom`, `descriptif_long`, `date_ajout`, `date_maj`, `id_user_ajout`, `id_user_maj`) VALUES (44, 4, 0, 'animation', 27, 0, 'Comment programmer mes sessions depuis l’espace pro ?', '<p>Depuis l\'espace pro, tu peux programmer une session de deux façons.</p><ul><li><b>Par thématique</b> : tu pars d\'un contenu ou d\'une thématique dans les catalogues de jeux, puis tu finalises la date et le format de la session.</li><li><b>Par date ou par récurrence</b> : tu poses d\'abord ton ou tes rendez-vous, puis tu complètes rapidement la programmation avec le jeu et le contenu souhaités.</li></ul><p>Ce second mode est particulièrement pratique pour planifier des animations régulières.</p>', NOW(), NOW(), 0, 0) ON DUPLICATE KEY UPDATE `id_sous_domaine` = VALUES(`id_sous_domaine`), `id_type_produit` = VALUES(`id_type_produit`), `zoning_code` = VALUES(`zoning_code`), `position` = VALUES(`position`), `online` = VALUES(`online`), `nom` = VALUES(`nom`), `descriptif_long` = VALUES(`descriptif_long`), `date_maj` = NOW(), `id_user_maj` = VALUES(`id_user_maj`);
INSERT INTO `support_faq` (`id`, `id_sous_domaine`, `id_type_produit`, `zoning_code`, `position`, `online`, `nom`, `descriptif_long`, `date_ajout`, `date_maj`, `id_user_ajout`, `id_user_maj`) VALUES (45, 4, 4, 'blind-test-general', 8, 0, 'Quelle est la durée d’un Blind Test ?', '<p>Un Blind Test dure en général <b>environ 30 minutes</b> dans son format standard.</p><p>Par défaut, il repose sur <b>40 extraits de 30 secondes</b>. Tu peux ensuite régler la durée des extraits entre <b>10 et 30 secondes</b>, et choisir au cas par cas de laisser jouer <b>un morceau en entier</b> si tu le souhaites.</p>', NOW(), NOW(), 0, 0) ON DUPLICATE KEY UPDATE `id_sous_domaine` = VALUES(`id_sous_domaine`), `id_type_produit` = VALUES(`id_type_produit`), `zoning_code` = VALUES(`zoning_code`), `position` = VALUES(`position`), `online` = VALUES(`online`), `nom` = VALUES(`nom`), `descriptif_long` = VALUES(`descriptif_long`), `date_maj` = NOW(), `id_user_maj` = VALUES(`id_user_maj`);
INSERT INTO `support_faq` (`id`, `id_sous_domaine`, `id_type_produit`, `zoning_code`, `position`, `online`, `nom`, `descriptif_long`, `date_ajout`, `date_maj`, `id_user_ajout`, `id_user_maj`) VALUES (46, 4, 0, 'general', 7, 0, 'Puis-je créer mes propres contenus ?', '<p><b>Oui.</b> Tu peux créer des <b>séries de quiz personnalisées</b> avec tes propres questions, réponses, fausses propositions et supports média, ainsi que des <b>playlists personnalisées</b> à partir d\'une <b>URL de playlist YouTube Music</b>.</p><p>Cela permet d\'adapter très facilement l\'animation à ton établissement, à ton événement ou à ton public.</p>', NOW(), NOW(), 0, 0) ON DUPLICATE KEY UPDATE `id_sous_domaine` = VALUES(`id_sous_domaine`), `id_type_produit` = VALUES(`id_type_produit`), `zoning_code` = VALUES(`zoning_code`), `position` = VALUES(`position`), `online` = VALUES(`online`), `nom` = VALUES(`nom`), `descriptif_long` = VALUES(`descriptif_long`), `date_maj` = NOW(), `id_user_maj` = VALUES(`id_user_maj`);
INSERT INTO `support_faq` (`id`, `id_sous_domaine`, `id_type_produit`, `zoning_code`, `position`, `online`, `nom`, `descriptif_long`, `date_ajout`, `date_maj`, `id_user_ajout`, `id_user_maj`) VALUES
(62, 4, 0, 'general', 3, 0, 'Comment fonctionnent les jeux Cotton ?', '<p>Une fois ta session programmée, il te suffit de l’ouvrir depuis ton espace Cotton le jour J pour lancer l’animation.</p><p>Selon le jeu et le format choisis, les joueurs rejoignent ensuite la session sur leur <b>smartphone</b> via le lien ou le QR code affiché, ou participent avec des <b>supports papier</b> préparés à l’avance.</p>', NOW(), NOW(), 0, 0)
ON DUPLICATE KEY UPDATE
`id_sous_domaine` = VALUES(`id_sous_domaine`),
`id_type_produit` = VALUES(`id_type_produit`),
`zoning_code` = VALUES(`zoning_code`),
`position` = VALUES(`position`),
`online` = VALUES(`online`),
`nom` = VALUES(`nom`),
`descriptif_long` = VALUES(`descriptif_long`),
`date_maj` = NOW(),
`id_user_maj` = VALUES(`id_user_maj`);
INSERT INTO `support_faq` (`id`, `id_sous_domaine`, `id_type_produit`, `zoning_code`, `position`, `online`, `nom`, `descriptif_long`, `date_ajout`, `date_maj`, `id_user_ajout`, `id_user_maj`) VALUES
(59, 4, 4, 'blind-test-general', 9, 0, 'Comment choisir le contenu de mon Blind Test ?', '<p>Depuis les catalogues de jeux, tu peux sélectionner une thématique adaptée à ton public parmi les playlists disponibles.</p><p>Tu peux explorer les sélections <b>À la une</b>, <b>Nouveautés</b> et <b>Thèmes</b>, ou créer une <b>playlist personnalisée</b> à partir d\'une <b>URL de playlist YouTube Music</b>.</p>', NOW(), NOW(), 0, 0),
(60, 4, 4, 'blind-test-general', 10, 0, 'Quelles sont les règles du jeu ?', '<p>Le Blind Test existe en version <b>numérique</b> et en version <b>classique</b>. En version numérique, les joueurs répondent sur smartphone. En version classique, les réponses se font sur papier.</p><p>Chaque bonne réponse rapporte <b>entre 1 et 10 points</b> selon le temps de réponse. En version numérique, tu peux afficher de <b>3 à 5 propositions</b> et choisir un affichage <b>titre + artiste</b> ou <b>titres uniquement</b>.</p>', NOW(), NOW(), 0, 0)
ON DUPLICATE KEY UPDATE
`id_sous_domaine` = VALUES(`id_sous_domaine`),
`id_type_produit` = VALUES(`id_type_produit`),
`zoning_code` = VALUES(`zoning_code`),
`position` = VALUES(`position`),
`online` = VALUES(`online`),
`nom` = VALUES(`nom`),
`descriptif_long` = VALUES(`descriptif_long`),
`date_maj` = NOW(),
`id_user_maj` = VALUES(`id_user_maj`);

INSERT INTO `support_faq` (`id`, `id_sous_domaine`, `id_type_produit`, `zoning_code`, `position`, `online`, `nom`, `descriptif_long`, `date_ajout`, `date_maj`, `id_user_ajout`, `id_user_maj`) VALUES
(61, 4, 4, 'animation', 26, 0, 'Quels conseils pouvez-vous me donner pour bien animer un Blind Test ?', '<p><b>Présente rapidement le fonctionnement avant le départ</b> et annonce les lots si tu en prévois.</p><p>Choisis une thématique adaptée à ton public, précise si les réponses se font sur smartphone ou sur papier, puis ajuste la durée des extraits selon le niveau de difficulté recherché.</p>', NOW(), NOW(), 0, 0)
ON DUPLICATE KEY UPDATE
`id_sous_domaine` = VALUES(`id_sous_domaine`),
`id_type_produit` = VALUES(`id_type_produit`),
`zoning_code` = VALUES(`zoning_code`),
`position` = VALUES(`position`),
`online` = VALUES(`online`),
`nom` = VALUES(`nom`),
`descriptif_long` = VALUES(`descriptif_long`),
`date_maj` = NOW(),
`id_user_maj` = VALUES(`id_user_maj`);



-- Blind Test split dynamique : conservation du bloc legacy blind-test (ids 40-42) en fallback,
-- ajout de deux variantes explicites pour pilotage front futur.
UPDATE `support_faq` SET `nom` = 'Principe du jeu', `descriptif_long` = '<p>Le Blind Test est un jeu musical basé sur la rapidité. Les joueurs doivent reconnaître le bon morceau, le bon titre ou le bon artiste au fil des extraits proposés.</p><p>Dans sa configuration standard, une session dure <b>environ 30 minutes</b>, sur la base de <b>40 extraits de 30 secondes</b> par défaut.</p>', `date_maj` = NOW() WHERE `id` = 40;
UPDATE `support_faq` SET `nom` = 'Règles du jeu', `descriptif_long` = '<p>Le Blind Test existe en version <b>numérique</b> et en version <b>classique</b>. En version numérique, les joueurs répondent sur smartphone. En version classique, les réponses se font sur papier.</p><p>Chaque bonne réponse rapporte <b>entre 1 et 10 points</b> selon le temps de réponse. Tu peux régler la durée des extraits entre <b>10 et 30 secondes</b>. Si tu le souhaites, tu peux aussi laisser jouer un morceau en entier, titre par titre.</p>', `date_maj` = NOW() WHERE `id` = 41;
UPDATE `support_faq` SET `nom` = 'Conseils', `descriptif_long` = '<p><b>Présente rapidement le fonctionnement avant le départ</b> et annonce les lots si tu en prévois.</p><p>Choisis une thématique adaptée à ton public et ajuste la durée des extraits selon le niveau de difficulté recherché.</p>', `date_maj` = NOW() WHERE `id` = 42;

INSERT INTO `support_faq` (`id`, `id_sous_domaine`, `id_type_produit`, `zoning_code`, `position`, `online`, `nom`, `descriptif_long`, `date_ajout`, `date_maj`, `id_user_ajout`, `id_user_maj`) VALUES
(47, 4, 4, 'blind-test-classique', 43, 0, 'Principe du jeu', '<p>Le Blind Test classique est un jeu musical basé sur la rapidité. Les joueurs écoutent les extraits diffusés puis notent leurs réponses sur papier.</p><p>Dans sa configuration standard, une session dure <b>environ 30 minutes</b>, sur la base de <b>40 extraits de 30 secondes</b> par défaut.</p>', NOW(), NOW(), 0, 0),
(48, 4, 4, 'blind-test-classique', 44, 0, 'Règles du jeu', '<p>Les réponses se font sur <b>papier</b>. Chaque bonne réponse rapporte <b>entre 1 et 10 points</b> selon le temps de réponse.</p><p>Tu peux régler la durée des extraits entre <b>10 et 30 secondes</b>. Si tu le souhaites, tu peux aussi laisser jouer un morceau en entier, titre par titre.</p>', NOW(), NOW(), 0, 0),
(49, 4, 4, 'blind-test-classique', 45, 0, 'Conseils', '<p><b>Distribue les supports avant le départ</b> et rappelle aux joueurs comment noter clairement leurs réponses.</p><p>Annonce la thématique, précise le mode de comptage des points et adapte la durée des extraits au niveau de difficulté souhaité.</p>', NOW(), NOW(), 0, 0),
(50, 4, 4, 'blind-test-numerique', 46, 0, 'Principe du jeu', '<p>Le Blind Test numérique est un jeu musical basé sur la rapidité. Les joueurs écoutent les extraits puis répondent sur smartphone pendant la session.</p><p>Dans sa configuration standard, une session dure <b>environ 30 minutes</b>, sur la base de <b>40 extraits de 30 secondes</b> par défaut.</p>', NOW(), NOW(), 0, 0),
(51, 4, 4, 'blind-test-numerique', 47, 0, 'Règles du jeu', '<p>Les joueurs répondent sur <b>smartphone</b>. Chaque bonne réponse rapporte <b>entre 1 et 10 points</b> selon le temps de réponse.</p><p>Tu peux régler la durée des extraits entre <b>10 et 30 secondes</b>. En version numérique, tu peux afficher de <b>3 à 5 propositions de réponse</b> et choisir un affichage <b>titre + artiste</b> ou <b>titres uniquement</b>. Si tu le souhaites, tu peux aussi laisser jouer un morceau en entier, titre par titre.</p>', NOW(), NOW(), 0, 0),
(52, 4, 4, 'blind-test-numerique', 48, 0, 'Conseils', '<p><b>Présente rapidement le fonctionnement avant le départ</b> et rappelle que la rapidité compte dans le score.</p><p>Pour une animation plus fluide et interactive, privilégie l\'affichage des propositions et ajuste la durée des extraits selon ton public.</p>', NOW(), NOW(), 0, 0)
ON DUPLICATE KEY UPDATE
`id_sous_domaine` = VALUES(`id_sous_domaine`),
`id_type_produit` = VALUES(`id_type_produit`),
`zoning_code` = VALUES(`zoning_code`),
`position` = VALUES(`position`),
`online` = VALUES(`online`),
`nom` = VALUES(`nom`),
`descriptif_long` = VALUES(`descriptif_long`),
`date_maj` = NOW(),
`id_user_maj` = VALUES(`id_user_maj`);

-- Cotton Quiz split dynamique : conservation des blocs legacy 2/4 séries (ids 34-39) en fallback,
-- ajout de deux variantes explicites pour pilotage front futur.
INSERT INTO `support_faq` (`id`, `id_sous_domaine`, `id_type_produit`, `zoning_code`, `position`, `online`, `nom`, `descriptif_long`, `date_ajout`, `date_maj`, `id_user_ajout`, `id_user_maj`) VALUES
(53, 4, 5, 'cotton-quiz-classique', 49, 0, 'Principe du Cotton Quiz', '<p>Le Cotton Quiz classique est un jeu de questions-réponses organisé en séries, sur des thématiques variées. Les joueurs répondent sur papier pendant la session.</p><p>Dans son format standard complet, une session dure <b>environ 30 minutes</b>. Chaque bonne réponse rapporte <b>10 points</b>.</p>', NOW(), NOW(), 0, 0),
(54, 4, 5, 'cotton-quiz-classique', 50, 0, 'Règles du jeu', '<p>Les joueurs répondent sur <b>papier</b>. Tu peux composer ton quiz avec plusieurs séries, dans la limite de <b>4 séries</b>.</p><p>Tu peux régler la durée des questions entre <b>30 secondes</b> et <b>1 minute</b>, et définir un temps de pause entre les séries, de <b>0 à 15 minutes</b>.</p>', NOW(), NOW(), 0, 0),
(55, 4, 5, 'cotton-quiz-classique', 51, 0, 'Conseils d\'animation', '<p><b>Présente le nombre de séries et le rythme de la partie avant de commencer.</b></p><p>Distribue les supports avant le départ, rappelle comment noter clairement les réponses et annonce les pauses à l\'avance si tu en utilises.</p>', NOW(), NOW(), 0, 0),
(56, 4, 5, 'cotton-quiz-numerique', 52, 0, 'Principe du Cotton Quiz', '<p>Le Cotton Quiz numérique est un jeu de questions-réponses organisé en séries, sur des thématiques variées. Les joueurs répondent sur smartphone pendant la session.</p><p>Dans son format standard complet, une session dure <b>environ 30 minutes</b>. Chaque bonne réponse rapporte <b>10 points</b>.</p>', NOW(), NOW(), 0, 0),
(57, 4, 5, 'cotton-quiz-numerique', 53, 0, 'Règles du jeu', '<p>Les joueurs répondent sur <b>smartphone</b>. Tu peux composer ton quiz avec plusieurs séries, dans la limite de <b>4 séries</b>.</p><p>Tu peux régler la durée des questions entre <b>30 secondes</b> et <b>1 minute</b>. En version numérique, tu peux afficher de <b>2 à 4 propositions de réponse</b> aux joueurs. Tu peux aussi définir un temps de pause entre les séries, de <b>0 à 15 minutes</b>.</p>', NOW(), NOW(), 0, 0),
(58, 4, 5, 'cotton-quiz-numerique', 54, 0, 'Conseils d\'animation', '<p><b>Présente le nombre de séries et le rythme de la partie avant de commencer.</b></p><p>Pour une animation plus fluide, rappelle le fonctionnement des réponses sur smartphone et annonce les pauses à l\'avance si tu en utilises.</p>', NOW(), NOW(), 0, 0)
ON DUPLICATE KEY UPDATE
`id_sous_domaine` = VALUES(`id_sous_domaine`),
`id_type_produit` = VALUES(`id_type_produit`),
`zoning_code` = VALUES(`zoning_code`),
`position` = VALUES(`position`),
`online` = VALUES(`online`),
`nom` = VALUES(`nom`),
`descriptif_long` = VALUES(`descriptif_long`),
`date_maj` = NOW(),
`id_user_maj` = VALUES(`id_user_maj`);


COMMIT;
